[build-system]
requires = ["setuptools", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[project]
name = "pyappexample"
version = "0.1.1"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["scipy>=1.11.4"]
